
#端口号，默认8080，可以自己改， 项目在设置的端口号启动
server:
  port: 8082
  #项目启动时在工程名前加上usercenter,springboot2.0以下的使用server.context-path
  servlet:
     context-path: /test
spring:
  datasource:
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: mysql
    url: jdbc:mysql://192.168.120.201:3306/ajb_vap?serverTimezone=UTC&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true  #设置开启热部署
  # activiti配置
  activiti:
    database-schema-update: true #是否每次都更新数据库:自动更新数据库结构
    check-process-definitions : false  # 默认为true --activti是否自动部署:自动检查、部署流程定义文件,就是在resource下的文件检查并部署;如果是false就不会自动部署
    history-level: full #历史记录存储等级：full最高级别
    db-history-used: true  # activiti7增加的：默认不生成历史信息表，设置为true就生成历史信息表
    process-defintition-location-prefix: classpath:/processes/  #实际流程存放的位置--流程定义文件存放目录
    #定时事件配置
    #启用作业执行器
    async-executor-activate: true
    #启用异步执行器
    job-executor-activate: true
  #jpa配置
  jpa:
    show-sql: true
    hibernate:
       ddl-auto: update
       naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
       dialect: org.hibernate.dialect.MySQL5Dialect

  kafka:
    bootstrap-servers: ${KAFKA_URL:192.168.120.201}:9092
    consumer:
      properties:
        sasl.mechanism: PLAIN
        security.protocol: SASL_PLAINTEXT
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="${KAFKA_PWD:admin-2019}";
      enable-auto-commit: false
      group-id: alarmdeal-consumer-group-test-2
      auto-commit-interval: 100
      auto-offset-reset: latest
      max-poll-records: 1000
      fetch-max-wait: 400 #最大等待时间
      fetch-min-size: 1 #最小消费字节数
    producer:
      enable-auto-commit: false # 是否自动提交offset
      retries: 0 # 重试次数
      acks: all # 应答级别:多少个分区副本备份完成时向生产者发送ack确认(可选0、1、all/-1)
      batch-size: 16384 # 批量大小
      buffer-memory: 33554432 # 生产端缓冲区大小
      properties:
        sasl.mechanism: PLAIN
        security.protocol: SASL_PLAINTEXT
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="${KAFKA_PWD:admin-2019}";
    listener:
      concurrency: 3

jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA512ANDAES_256
    password: fada6bd719ec7d2befe1986a02661b23
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    poolSize: 3
    keyObtentionIterations: 1000